name: couldai_user_app
description: "A password management app."
publish_to: 'none'
version: 1.0.0+1

environment:
sdk: ^3.7.2

dependencies:
flutter:
sdk: flutter
cupertino_icons: ^1.0.8
supabase_flutter: ^2.9.1
hive: ^2.2.3
hive_flutter: ^1.1.0
encrypt: ^5.0.3

flutter:
uses-material-design: true
